ALTER TABLE categories MODIFY COLUMN image VARCHAR(1024) NULL;
ALTER TABLE product_images MODIFY COLUMN image VARCHAR(1024) NULL;
ALTER TABLE users MODIFY COLUMN avatar VARCHAR(1024) NULL;
ALTER TABLE order_items MODIFY COLUMN product_image VARCHAR(1024) NULL;
