"use client";

import { ArrowLeft, Ban, CheckCircle2, CreditCard, MapPin, PackageSearch, Phone, UserRound } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CatalogImage } from "@/components/catalog/catalog-image";
import { getApiErrorMessage } from "@/lib/api-error";
import { formatPrice } from "@/lib/catalog-format";
import { formatDateTime, orderStatusLabel } from "@/lib/order-format";
import { orderService } from "@/services/order-service";
import type { Order } from "@/types/order";

export function OrderDetailClient({id}:{id:number}){const [order,setOrder]=useState<Order|null>(null);const [error,setError]=useState<string|null>(null);const [canceling,setCanceling]=useState(false);useEffect(()=>{let active=true;orderService.findOne(id).then(data=>active&&setOrder(data)).catch(e=>active&&setError(getApiErrorMessage(e)));return()=>{active=false};},[id]);
  if(error)return <main className="catalog-main"><div className="catalog-empty"><PackageSearch size={38}/><h1>Không thể mở đơn hàng</h1><p>{error}</p><Link className="primary-button" href="/orders">Danh sách đơn hàng</Link></div></main>;
  if(!order)return <main className="catalog-main"><p className="commerce-state">Đang tải chi tiết đơn hàng...</p></main>;
  const cancelOrder=async()=>{if(!window.confirm("Bạn muốn hủy đơn hàng này? Tồn kho và lượt coupon sẽ được hoàn lại."))return;setCanceling(true);setError(null);try{setOrder(await orderService.cancel(order.id));}catch(e){setError(getApiErrorMessage(e));}finally{setCanceling(false);}};
  return <main className="catalog-main order-detail-main"><Link className="commerce-back" href="/orders"><ArrowLeft size={16}/>Tất cả đơn hàng</Link>{error&&<p className="catalog-notice error">{error}</p>}<header className="order-detail-heading"><div><span className={`order-status ${order.status}`}>{orderStatusLabel[order.status]??order.status}</span><h1>Đơn hàng #{order.id}</h1><p>Đặt lúc {formatDateTime(order.createdAt)}</p></div><div className="order-heading-actions"><strong>{formatPrice(order.total)}</strong>{order.status==="pending"&&order.payment?.status!=="completed"&&<button type="button" className="secondary-button danger" disabled={canceling} onClick={()=>void cancelOrder()}><Ban size={16}/>{canceling?"Đang hủy...":"Hủy đơn"}</button>}</div></header><div className="order-detail-layout"><div><section className="order-detail-section"><h2>Sản phẩm</h2>{order.items.map(item=><article className="order-product" key={item.id}><Link href={`/products/${item.productSlug}`}><CatalogImage src={item.productImage} alt={item.productName}/></Link><div><Link href={`/products/${item.productSlug}`}><strong>{item.productName}</strong></Link><p>{formatPrice(item.unitPrice)} / {item.productUnit??"sản phẩm"} · Số lượng {item.quantity}</p></div><strong>{formatPrice(item.lineTotal)}</strong></article>)}</section><section className="order-detail-section"><h2>Lịch sử trạng thái</h2><ol className="order-timeline">{order.statusHistory.map(item=><li key={item.id}><CheckCircle2 size={18}/><div><strong>{orderStatusLabel[item.status]??item.status}</strong><p>{item.note}</p><small>{formatDateTime(item.changedAt)}</small></div></li>)}</ol></section></div><aside><section className="order-address"><h2>Địa chỉ nhận hàng</h2><p><UserRound size={16}/>{order.recipientName}</p><p><Phone size={16}/>{order.recipientPhone}</p><p><MapPin size={16}/>{order.shippingAddress}, {order.shippingCity}</p></section>{order.payment&&<section className="order-totals"><h2><CreditCard size={17}/>Thanh toán</h2><div><span>Phương thức</span><strong>{order.payment.method==="cod"?"COD":order.payment.method.toUpperCase()}</strong></div><div><span>Trạng thái</span><strong>{order.payment.status==="completed"?"Đã thanh toán":order.payment.status==="failed"?"Không thành công":"Chờ thanh toán"}</strong></div>{order.payment.transactionId&&<div><span>Mã giao dịch</span><strong>{order.payment.transactionId}</strong></div>}</section>}<section className="order-totals"><div><span>Tạm tính</span><strong>{formatPrice(order.subtotal)}</strong></div><div><span>Phí giao hàng</span><strong>{order.shippingFee===0?"Miễn phí":formatPrice(order.shippingFee)}</strong></div>{order.discountAmount>0&&<div className="discount-row"><span>Giảm giá {order.couponCode&&`(${order.couponCode})`}</span><strong>−{formatPrice(order.discountAmount)}</strong></div>}<div><span>Tổng cộng</span><strong>{formatPrice(order.total)}</strong></div></section></aside></div></main>;
}
